scorelab/fact-Bounty

fact-bounty-server/config/passport.js, fact-bounty-server/models/Story.js, fact-bounty-server/models/User.js, fact-bounty-server/package-lock.json, fact-bounty-server/package.json, fact-bounty-server/routes/api/story.js, fact-bounty-server/server.js
- Added the basic endpoints to display stories in the feed
=> Implement the API routes for stories

fact-bounty-client/src/pages/main/Posts.sass, fact-bounty-client/src/pages/main/components/Post.js
Cleaner design for post component
=> Redesign post component

db/dump/stories.json, db/dump/users.json
Closes https://github.com/scorelab/fact-Bounty/issues/16
=> Update stories.json and users.json as per json conventions

fact-bounty-server/package.json, fact-bounty-server/routes/api/story.js, fact-bounty-server/routes/api/user.js
The wrong orientation of req, res results in no response.
Also, API was not running in dev mode, fixed
Fixes https://github.com/scorelab/fact-Bounty/issues/18
=> Fix api hang issue

fact-bounty-server/controllers/story.js, fact-bounty-server/controllers/user.js, fact-bounty-server/routes/api/story.js, fact-bounty-server/routes/api/user.js, fact-bounty-server/routes/index.js
Moved all functions from routes to controllers. 
Simplified routes folder.
=> Improve files structure in server

fact-bounty-server/controllers/user.js, fact-bounty-server/models/user.js
Added password hashing and compare logic in user schema
=> Added password hashing and compare as a part of user schema

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Add basic templates for issue and pull request.
=> Add general contributing guidelines

fact-bounty-client/src/actions/authActions.js, fact-bounty-client/src/pages/dashboard/actions/dashboardActions.js
-removed unnecessary loginUser and registerUser function from actions/authActions.js because those are covered in separate login and register components.
-in dashboardActions.js  passing  setCurrentUser({}) in dispatch which is imported from actions/authActions.js , which will set current user to empty object and redirect to login page
closing #58
=> fixed logout not redirect to login page issue

fact-bounty-client/package-lock.json, fact-bounty-client/src/core/theme.js, fact-bounty-client/src/shared/components/TopNavBar.js, fact-bounty-server/controllers/story.js, fact-bounty-server/routes/api/story.js
Change theme color and fixed mixedVote api bug
=> Change theme color plus bug fixes

.dockerignore, README.md, docker-compose.yml, fact-bounty-client/.dockerignore, fact-bounty-client/Dockerfile, fact-bounty-server/.dockerignore, fact-bounty-server/Dockerfile
Add dockerfile for server and client and docker-compose.yml which executes both.
Add instructions to docker setup in readme.md
=> Dockerize App

fact-bounty-client/package-lock.json, fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/register/components/Register.js, fact-bounty-server/package-lock.json
This pull Request Fixes the login and registration view with material components
This fixes the current issues of view in registration and login.
Login UI
Register UI
Issue #68
=> fix login and register material view

fact-bounty-client/package-lock.json, fact-bounty-client/package.json
add link to issue and pr template in readme.
Fix vulnerabilities in package-lock client side by `npm audit fix`
=> Fix vulnerabilities in package-lock client

fact-bounty-client/src/actions/authActions.js, fact-bounty-client/src/pages/dashboard/actions/dashboardActions.js, fact-bounty-client/src/pages/main/components/Post.js
Remove unwanted variables and imports
=> Removed unwanted variables and imports

fact-bounty-flask/README.md, fact-bounty-flask/app.py, fact-bounty-flask/requirements.txt
Also added loading of environment variables from .env file in app
Add corresponding changes to requirements
Closes https://github.com/scorelab/fact-Bounty/issues/94
=> Add readme for flask api

fact-bounty-client/src/pages/register/components/Register.js
This pull request adds password compare feature to signup to prevent 1 round trip to server #96
=> feat: #96(compare password in signup)

fact-bounty-client/src/shared/components/TopNavBar.js
[Issue](https://github.com/scorelab/fact-Bounty/issues/62)
=> fix: #62 (Login from Navbar not working)

fact-bounty-client/src/shared/components/TopNavBar.js
It improves the design of navbar  #108 
It also adds signup from the navbar
`closes #108 `
=> fix: #108 improved NavBar design

docker-compose.yml, fact-bounty-flask/Dockerfile
#113 
Dockerfile for fact-bounty-flask and added build of the `flask` to docker-compose.yml
=> Dockerfile added for flask and updated docker-compose.yml

fact-bounty-client/src/pages/register/components/Register.js
Before fixing the issue:
After fixing the issue
=> Issue #129 is fixed

fact-bounty-flask/tests/authentication/login.py, fact-bounty-flask/tests/authentication/register.py, fact-bounty-flask/tests/story_test.py
`assert` checks updated in Flask authentication and stories API's tests.
#150
=> assert checks updated in Flask API's tests

fact-bounty-client/src/pages/login/components/Login.js
=> Added link to register from login page

fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/register/components/Register.js
1. Added link to register page from the login page
2. Added link to the login page from register page
Closes #67. @ivantha Please review.
Screenshots -
=> Added links on register and login pages

fact-bounty-flask/__init__.py, fact-bounty-flask/requirements.txt
@root5533 @ivantha 
Cross-origin request will not be blocked. I have added `Flask-Cors` dependency for resolving the CORS problem.
Fixes #167 
**Thanks**
=> CORS added

fact-bounty-client/src/pages/main/actions/postActions.js, fact-bounty-flask/api/controllers/stories.py, fact-bounty-flask/api/controllers/users.py, fact-bounty-flask/api_es/controllers/story.py
Now data is received as json in api 
Previously data was extracted as form data
Change route of requests to flask route
Fixes https://github.com/scorelab/fact-Bounty/issues/156
=> Now data is recieved as json in api

fact-bounty-client/src/pages/dashboard/components/Dashboard.js, fact-bounty-client/src/shared/components/TopNavBar.js
Improved navbar design
Presently navbar looks: 
Navbar in PR
Put closes #134  in your comment and commit message to auto-close the issue that your PR fixes (if such).
=> improved navbar

fact-bounty-flask/api/controllers/users.py
Querying with JSON data instead of form data.
@ivantha @Anmolbansal1 
Fixes #174
=> Register API bug fixed and docstring added

fact-bounty-client/public/index.html
This commit will change the app title to "Fact-Bounty" which previously was deafult "ReactApp"
=> change app title

fact-bounty-flask/tests/authentication/login.py, fact-bounty-flask/tests/authentication/register.py
As API's now take JSON data as input, some of the Flask's API like authentication requires changes in it like posting JSON data with `POST` request.
@ivantha @Anmolbansal1 
**Thanks**
=> Test bugs fixed as API's got updated

db/add_es.py, db/dump/stories.json, fact-bounty-flask/api_es/controllers/story.py, fact-bounty-flask/config.py
Now elasticsearch endpoints of api are correctly working.
Add sample script to populate data in elasticsearch database
=> fixed elasticsearch endpoints

fact-bounty-flask/README.md
Update instruction for live reload
Add elasticsearch instructions
Closes https://github.com/scorelab/fact-Bounty/issues/116
=> Add live reload

fact-bounty-client/src/actions/types.js, fact-bounty-client/src/core/errorReducers.js, fact-bounty-client/src/core/types.js, fact-bounty-client/src/pages/login/actions/authActions.js, fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/register/actions/newUserActions.js, fact-bounty-client/src/pages/register/components/Register.js, fact-bounty-client/src/shared/actions/errorActions.js, fact-bounty-client/src/shared/components/Snackbar.js, fact-bounty-client/src/shared/components/TopNavBar.js
- #179 
- Refactored code, as `componentWillReceiveProps` has been depreciated
- Removed warnings 
**Code formatting**
closes #179
=> fix: #179(Connection errors are not handled in frontend)

fact-bounty-client/package-lock.json, fact-bounty-client/package.json, fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/register/actions/newUserActions.js, fact-bounty-client/src/pages/register/components/Register.js
The proxy port is now 5000 same as Flask default port
Fixed the validations for login and register forms like:
Fixes #204
=> error handling of register and login forms, proxy port changed as same as flask default port

fact-bounty-client/src/pages/register/components/Register.js
=> fix: confirm password error #212

fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/register/components/Register.js
=> fix: Proptype errors #214

fact-bounty-client/src/pages/login/actions/authActions.js
@root5533 @ivantha 
Resolved two errors in the authentication code 
**1.** Added check for `err.response` 
**2.** `token` varialble declaration and wrongly assigned bug fixed as
```js 
const token = res.data.access_token 
```
Fixes #194
=> jwt_token error resolved and err.response checks included in action

LICENSE
=> update LICENSE file

.travis.yml
=> Update travis for elasticsearch

fact-bounty-flask/__init__.py
As more commands will get added in `__init__.py` file, if it will be structured it will be more readable to the user :slightly_smiling_face:
=> structurize the __init__.py file

fact-bounty-client/src/App.js, fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/main/components/MainLayout.js, fact-bounty-client/src/pages/main/components/Post.js, fact-bounty-client/src/pages/main/components/Posts.js, fact-bounty-client/src/pages/register/components/Register.js, fact-bounty-client/src/shared/OAuthContainer/GoogleContainer.js
- Removed old commented file imports
- Grouped all direct imports and relative imports in old components. (This Convention is followed in new components).
=> Improved readability of import statements

fact-bounty-client/src/core/store.js
=> Redux devtool optional

fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/register/components/Register.js, fact-bounty-client/src/shared/OAuthContainer/FacebookContainer.js, fact-bounty-client/src/shared/OAuthContainer/GoogleContainer.js
Fixed all console warnings.
Fixes #247
=> Fixed the console warnings

fact-bounty-client/package.json, fact-bounty-client/src/pages/login/components/Login.js, fact-bounty-client/src/pages/register/components/Register.js, fact-bounty-client/src/shared/OAuthContainer/FacebookContainer.js, fact-bounty-client/src/shared/OAuthContainer/GoogleContainer.js, fact-bounty-client/src/shared/OAuthContainer/index.css
The UI of the social login is improved.
closes #236
=> Login and Register UI improved

fact-bounty-client/src/shared/OAuthContainer/FacebookContainer.js, fact-bounty-client/src/shared/OAuthContainer/GoogleContainer.js, fact-bounty-client/src/shared/OAuthContainer/actions/OAuthUser.js, fact-bounty-client/src/shared/OAuthContainer/index.js, fact-bounty-flask/api/controllers/users.py
- Fixed googeContainer component earlier request was not sent to the server and added toast in case of failure
- Fixed facebookContainer component earlier request was not sent to the server
- Fixed backend logic for social auth and small errors.
closes #245
=> fixed Social login #245

fact-bounty-client/src/App.js, fact-bounty-client/src/App.sass, fact-bounty-client/src/pages/main/components/MainLayout.js
Issue #251 due to my bad implementation of 404 page in PR #241😅
=> fix: routes

README.md
Listed basic steps for installation and starting the server of elasticsearch in README.md file.
Fixes #261 
**Thanks**
=> feat: add elasticsearch install and starting the server instructions

.travis.yml, docker-compose.yml
Integrated docker-compose with Travis build.
@ivantha @Anmolbansal1
=> docker-compose integrated in travis build

README.md
fixed the broken link destination of link Flask in README.md file.
=> fixed #267

fact-bounty-client/src/App.js, fact-bounty-client/src/pages/main/Posts.sass, fact-bounty-client/src/pages/notFound/components/404.js, fact-bounty-client/src/pages/notFound/styles/index.css, fact-bounty-client/src/shared/OAuthContainer/GoogleContainer.js, fact-bounty-client/src/shared/components/TopNavBar.js
Due to conflicting CSS image in homepage were squashed, it is now fixed with this PR
closes #253
=> image size fix

fact-bounty-client/src/pages/main/Posts.sass
Added styling to Posts.sass so the news posts will be responisive to different display sizes.
Closes #259
=> News non responsive fixed

.dependabot/config.yml
- Change frequency from live to weekly
- Allow only security updates
Closes #311
=> Update depandabot configurations

README.md, fact-bounty-flask/api/app.py, fact-bounty-flask/prod.txt, fact-bounty-flask/requirements.txt
Adds db config url variable example to readme ".env" example section and adds updated version on **pymysql** to project requirements
=> Adds db config url example to readme

fact-bounty-client/package.json, fact-bounty-client/src/constants/ApiConstants.js
Adds post build script and prod api url constant
Solves #347 and #348
=> Adds post build script and prod api url constant

.vscode/settings.json, Crawlers/requirements.txt, fact-bounty-flask/api/app.py, fact-bounty-flask/api/crawler/__init__.py, fact-bounty-flask/api/crawler/controller.py, fact-bounty-flask/api/crawler/utils.py, fact-bounty-flask/api/crawler/views.py, fact-bounty-flask/docker.txt, fact-bounty-flask/prod.txt, fact-bounty-flask/requirements.txt
Add scrapyd in crawlers
Add scrapydAPI and APScheduler to flask API
Add new route /api/crawler to control crawlers
Add /cron_job route in it to control jobs of crawling
=> Feat: cron job of crawler from Flask API

fact-bounty-flask/api/app.py, fact-bounty-flask/api/config.py, fact-bounty-flask/api/extensions.py, fact-bounty-flask/api/helpers.py, fact-bounty-flask/api/util/__init__.py, fact-bounty-flask/api/util/controller.py, fact-bounty-flask/api/util/views.py, fact-bounty-flask/requirements.txt
Add SMTP server with Flask-Mail extension
Add error mailing in production config
Add new blueprint 'utils' to handle miscellaneous routes
Add asynchronous mailing function with threading
Add Flask API route for Contact Us form
=>  feat: add SMTP server and contact us route to flask API

fact-bounty-client/src/AppRouter.js, fact-bounty-client/src/components/NavBar/Links/PublicLinks.js, fact-bounty-client/src/pages/Twitter/Twitter.jsx, fact-bounty-client/src/pages/Twitter/index.js, fact-bounty-client/src/pages/Twitter/styles.sass
Simple front end design for twitter keyword search
=> Twitter search from Hoaxy front end

Crawlers/news_sites/settings.py, fact-bounty-flask/api/config.py, fact-bounty-flask/api/stories/controller.py
make index static for crawlers
=> make elasticsearch index an environment variable for flask API

README.md
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
**Code formatting**
Put `closes #XXXX` in your comment and commit message to auto-close the issue that your PR fixes (if such).
=> Add travis badge in readme

fact-bounty-flask/api/stories/controller.py
Fix error of flask voting route AttributeError: 'BaseQuery' object has no attribute 'save'
=> [Fix] voting API error AttributeError

fact-bounty-flask/api/stories/controller.py
=> [Fix] Update vote value in sql table

fact-bounty-client/public/index.html, fact-bounty-client/public/static/css/external.css, fact-bounty-client/src/pages/TwitterGraph/TwitterGraph.jsx, fact-bounty-client/src/pages/TwitterGraph/js/graph.js, fact-bounty-client/src/pages/TwitterGraph/js/main.js, fact-bounty-client/src/pages/TwitterGraph/styles.sass
=> Fix toggle node function

fact-bounty-client/public/index.html, fact-bounty-client/src/pages/TwitterGraph/TwitterGraph.jsx, fact-bounty-client/src/styles/external.css, fact-bounty-client/src/styles/style.sass
Bug fixes on modal in twitter graph
=> Modal bug fixes

fact-bounty-client/src/components/NavBar/NavBar.jsx
- This PR will add a link to the Fact Bounty logo which links to the landing page
closes #391
=> [FEAT] Adds landing page link to logo in nav bar

Crawlers/news_sites/pipelines.py, db/create_index.py
Create new script to create index with specified data type of columns.
Change  format of news in crawlers
=> Change data type of date column from string to date

fact-bounty-flask/api/stories/controller.py
=> Sort news data while fetching from elasticsearch

fact-bounty-flask/api/admin/__init__.py, fact-bounty-flask/api/admin/controller.py, fact-bounty-flask/api/admin/views.py, fact-bounty-flask/api/app.py, fact-bounty-flask/requirements.txt
Add new dependency psutil
Add new route '/api/admin/system' to return cpu, ram, disk and io usage of instance
=> Add new admin API in flask

fact-bounty-client/src/pages/Landing/Landing.jsx
- This PR is Quick fix of issue: #408
Closes #408
=> Quick fix of issue: 408

fact-bounty-client/src/pages/TwitterGraph/TwitterGraph.jsx, fact-bounty-client/src/pages/TwitterGraph/external.css, fact-bounty-client/src/pages/TwitterGraph/js/graph.js, fact-bounty-client/src/pages/TwitterGraph/js/main.js, fact-bounty-client/src/pages/TwitterGraph/js/twitter_search_timeline.js, fact-bounty-client/src/pages/TwitterGraph/nv.d3.css, fact-bounty-client/src/pages/TwitterGraph/styles.sass
=> Timeline graph for twitter

fact-bounty-client/src/pages/TwitterGraph/TwitterGraph.jsx, fact-bounty-client/src/pages/TwitterGraph/js/main.js, fact-bounty-client/src/pages/TwitterGraph/js/twitter.js, fact-bounty-client/src/pages/TwitterGraph/styles.sass
Add animation control buttons to twitter graphs
=> Animation Control Buttons

fact-bounty-client/src/components/PostsList/PostsList.jsx
=> Fix infinite scroll issue

Crawlers/news_sites/spiders/adaDeranaSinhala.py, Crawlers/news_sites/spiders/hiru.py, Crawlers/news_sites/spiders/hirufm.py, Crawlers/news_sites/spiders/hotnews.py, Crawlers/news_sites/spiders/lankahit.py, Crawlers/news_sites/spiders/neth.py, Crawlers/news_sites/spiders/nfsinhala.py, Crawlers/news_sites/spiders/rg.py, Crawlers/news_sites/spiders/shaagossip.py
Add, the more web crawlers files for following news sites;
- http://sinhala.adaderana.lk/morehotnews.php
- https://www.newsfirst.lk/sinhala/category/local/
- http://www.hirunews.lk/sinhala/local-news.php
- http://gossip.hirufm.lk/gossipnews/
- https://www.lankahotnews.net
- http://gossip.shaafm.lk/gossipnews/
- http://sinhala.lankahitgossip.com/category/hit-gossip-news/
- http://www.rategossip.com/all-page.html
- http://nethgossip.lk/category/9
closes #417
=> Add new crawlers files

fact-bounty-client/src/AppRouter.js, fact-bounty-client/src/components/DashboardSideNav/DashboardSideNav.jsx, fact-bounty-client/src/components/NavBar/Links/PrivateLinks.js, fact-bounty-client/src/components/NavBar/Links/PublicLinks.js, fact-bounty-client/src/components/SwipeableDrawer/Links/PrivateLinks.js, fact-bounty-client/src/components/SwipeableDrawer/Links/PublicLinks.js, fact-bounty-client/src/pages/Dashboard/Dashboard.jsx, fact-bounty-client/src/pages/Landing/Landing.jsx
- This PR will change the routing structure of the web app, the dashboard will be private and can only be accessed after login and the post list will be public, and fixes some broken links 
closes #427 and  #426
=> [Improvement] Changes routing structure

fact-bounty-flask/app.py
-  This Pr is a quick fix for the server side routes issue #434
closes #434
=> Quick fix for server side routes issue

fact-bounty-client/src/components/PostItem/PostItem.jsx, fact-bounty-client/src/pages/PostDetailView/PostDetailView.jsx
- This PR will add support to show "time passed" for posts
**Screen Shot**
closes #430
=> Adds time passed feature to post dates using moment Js

Crawlers/scrapy.cfg, README.md, fact-bounty-flask/app.py
- Minnor changes [Prep for deployment]
=> Minnor changes

fact-bounty-client/src/AppRouter.js, fact-bounty-client/src/components/NavBar/Links/PrivateLinks.js, fact-bounty-client/src/components/NavBar/Links/PublicLinks.js, fact-bounty-client/src/pages/Landing/Landing.jsx, fact-bounty-client/src/pages/Landing/style.sass, fact-bounty-client/src/pages/Tweets/Tweets.jsx, fact-bounty-client/src/pages/Tweets/index.js, fact-bounty-client/src/pages/Tweets/style.sass
Adds a tweets page to view all tweets.
=> Add tweets page

.idea/encodings.xml, .idea/fact-Bounty.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, Crawlers/twitter_accounts/adaderana.py, fact-bounty-flask/requirements.txt
Created a python script for scraping the data such as tweets ID, tweet, text, created time of the tweet and author of the tweet from a given twitter screen name (eg: adaderana) by using Twitter API. It was configured as a cron job by using python setInterval() method and extracted data are saved in a elasticsearch index.
closes #443
=> Add tweets scrape

README.md
=> Update README with Docker compose Environment Variables

fact-bounty-client/src/components/PostItem/PostItem.jsx, fact-bounty-client/src/components/PostItem/style.sass, fact-bounty-client/src/components/VoteButtons/VoteButtons.jsx, fact-bounty-client/src/components/VoteButtons/style.sass
Redesigned the PostItem and VoteButtons with regard to the actual component, icon components, and the SASS.
The previous card layout is not very usable on mobile devices. This pull request, upon a media query, breaks the content into a column layout, shifts the voting buttons inwards so that they don't take up screen real estate that could be used for displaying content, and makes the buttons bigger so that users can more easily click the buttons.
Ran tests
closes #10
=> Update UI for increased mobile responsiveness

codefresh.yml
It helps building pipeline to improve docker build
=> Add codefresh.yml

OAuthdSetup.md, README.md
Set up oauthd on local system :)
=> Added steps of setting up oauthd daemon locally in OAuthSetup.md

fact-bounty-flask/tests/test_story.py
Fix test class title
Add new test for single story
=> Update stories test

fact-bounty-flask/tests/test_admin.py, fact-bounty-flask/tests/test_crawler.py
Added unit tests for the previously untested admin and crawler routes. With this, the fetching of the information of all cron jobs, fetching of crawler jobs and initiation, and the fetching of system panel information is all tested for a valid response and expected values/data types.
Under development, it would be helpful to have initial unit tests for these two routes as it can help contributors easily identify any breaking changes and potentially spot issues with their code.
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI. …
=> Add Admin and Crawler Unit Tests

fact-bounty-flask/api/stories/controller.py, fact-bounty-flask/api/stories/model.py, fact-bounty-flask/api/stories/views.py
- Added comment routes to the story controller
- Add ability to load a user's comments (LoadUserComments)
- Add ability to update a comment (ChangeComment), also used to create as it will create the comment if it does not already exist, similar to voting
- Add ability to delete comments (DeleteComment)
- Add appropriate comment model
- Add respective URL rules
Comments enhance the experience of the platform by adding a communication medium for users to help each other contribute to validating other posts. With this, people can enter into discussions regarding the validity of a post's factuality. Additionally, this …
=> Add Commenting Support in Backend

fact-bounty-client/src/pages/Login/Login.jsx
Fixes html entities being shown problem. Fixed by adding `;` beside them.
**Fixed UI**
Closes #489
=> fixed html entities problem

README.md
Replaced `Rename` with `Duplicate and rename` in **REAME.md**. If **.env.example** is renamed, then it will get removed from master. So duplicating as **.env** seems a good idea. <br>
Just a one word change so i guess no need of testing it. <br>
**Closing issues** 
Closes #487 .
=> doc(readme): replaced `Rename`with `Duplicate and rename`

Crawlers/twitter_accounts/azzamameen.py
**Details**
changed the following in save_es function:
```   "_index": "twitter_index",
"_type": "AzzamAmeen", ```     twitter username
changed the following in Main:
```   get_all_tweets("AzzamAmeen")
thr = threading.Thread(target=get_all_tweets("AzzamAmeen")) ``` 
Successful in 4m — Build Passed by Travis Cl
=> Added crawler for Twitter account "Azzam Ameen"

fact-bounty-flask/api/app.py
Previously there was no exception catch logging. So added try except clause which prints error if thrown. 
**Error log example**
Closes #494.
=> [Error Track]: Added try except clause

fact-bounty-flask/api/stories/controller.py, fact-bounty-flask/api/user/controller.py, fact-bounty-flask/docs/stories/change_vote_count.yml, fact-bounty-flask/docs/stories/get_all.yml, fact-bounty-flask/docs/stories/get_by_id.yml, fact-bounty-flask/docs/stories/get_range.yml, fact-bounty-flask/docs/stories/load_user_vote.yml, fact-bounty-flask/docs/users/login.yml
**Details**
1. Added all stories routes doc mentioned in issue #468. To make some stories routes doc work, i had to add login route doc too.  
2. Added two tags: `Stories` and `Auth`.
**Screenshots**
#468
=> [DOC] Stories and auth route doc

fact-bounty-flask/tests/test_admin.py, fact-bounty-flask/tests/test_crawler.py, fact-bounty-flask/tests/test_login.py, fact-bounty-flask/tests/test_register.py, fact-bounty-flask/tests/test_story.py
**Details**
Appended **fact-bounty** folder path to `sys.path` which fixed the `no module` problem.
#472 
**Note**
There are many still errors in test files that needs to be fixed. And i would suggest to reduce the duplication of code present in all tests file( **setup** and **tearDown** function ).
=> [FIX:472] Appended system path

fact-bounty-client/src/components/DashboardSideNav/DashboardSideNav.jsx, fact-bounty-client/src/helpers/twitter.js, fact-bounty-client/src/pages/Dashboard/Dashboard.jsx, fact-bounty-client/src/pages/TweetSearch/TweetSearch.jsx, fact-bounty-client/src/pages/TweetSearch/index.js, fact-bounty-client/src/pages/TweetSearch/style.sass, fact-bounty-client/src/redux/actions/twitterActions.js, fact-bounty-client/src/redux/reducers/twitterReducers.js
**Please provide enough information so that others can review your pull request:**
Added a Twitter request helper (for making Tweet search API requests), actions and relevant reducers, store "schema" change, and a TwitterSearch component/page in order to add the ability to search for Tweets by keyword.
Allows the user to search for tweets similarly to how they would search for posts/"stories".
**Code formatting**
Code linted.
=> Search Tweets Feature

README.md, fact-bounty-flask/api/user/controller.py, fact-bounty-flask/api/user/model.py, fact-bounty-flask/api/user/views.py
- Added **Forgot Password** feature.
- Created *three* functions(server): `ForgotPassword`, `AuthVerificationToken` and `ResetPassword` in user controller.
- Added `verificationToken` column(unique, not null)  in user table. This gets populated at the time of signup. Used **uuid4** to generate random unique token.
- Used **smtplib** for sending mail.
- User clicks on `ForgotPassword` at `Login` page.
- User gets routed to `/forgotPassword`
- User enters email and then click on `Send verification token`.
- New form appears.
- User receives email which contains token.
- User copies and paste the token to `Verification Token` input.
- Clicks on `Verify token`.
- User gets routed to `/resetPassword/:token`.
- User populates the new form with `old password, new password and confirm password` …
=> [FEAT] Forgot Password : Server

fact-bounty-client/src/AppRouter.js, fact-bounty-client/src/pages/ForgotPassword/ForgotPassword.jsx, fact-bounty-client/src/pages/ForgotPassword/ForgotPassword.style.js, fact-bounty-client/src/pages/ForgotPassword/index.js, fact-bounty-client/src/pages/ResetPassword/ResetPassword.jsx, fact-bounty-client/src/pages/ResetPassword/ResetPassword.style.js, fact-bounty-client/src/pages/ResetPassword/index.js, fact-bounty-client/src/redux/actions/actionTypes.js, fact-bounty-client/src/redux/actions/authActions.js, fact-bounty-client/src/redux/actions/successActions.js, fact-bounty-client/src/redux/reducers/index.js, fact-bounty-client/src/redux/reducers/successReducers.js, fact-bounty-client/src/services/AuthService.js
- Added **Forgot Password** feature.
- Created *two* components(client): `ForgotPassword` and `ResetPassword` .
- User clicks on `ForgotPassword` at `Login` page.
- User gets routed to `/forgotPassword`
- User enters email and then click on `Send verification token`.
- New form appears.
- User receives email which contains token.
- User copies and paste the token to `Verification Token` input.
- Clicks on `Verify token`.
- User gets routed to `/resetPassword/:token`.
- User populates the new form with `old password, new password and confirm password` and then click on `Reset password`.
- If everything goes correct, password changes and user will be routed to login page.
**Closing issue**
#79.
=> [FEAT] Forgot Password - Frontend

fact-bounty-flask/api/user/controller.py, fact-bounty-flask/docs/users/login.yml, fact-bounty-flask/docs/users/logout_access.yml, fact-bounty-flask/docs/users/logout_refresh.yml, fact-bounty-flask/docs/users/oauth.yml, fact-bounty-flask/docs/users/register.yml, fact-bounty-flask/docs/users/token_refresh.yml
**Details**
1. Added user routes documentation as mentioned in issue #469. 
2. Changed tag name from *Auth* to *User*.
**Screenshots**
#469
=> [DOC] User routes

fact-bounty-flask/api/user/controller.py, fact-bounty-flask/api/user/views.py
Added controllers allowing the frontend to make requests to the backend in order to fetch the logged in user's name and email.
Also allows for a POST request to change the user's information.
Allows for the viewing and changing of a user's information from the frontend.
Tested with a docker build.
**Code formatting**
Follows the project's formatting.
=> Add backend routes for profile viewing and editing

fact-bounty-client/src/components/ContactUsForm/style.sass
Made the footer stick to bottom of the landing page.
=> Sticky Footer

fact-bounty-flask/api/commands.py
The Travis-CI build was passing even though all the subsequent tests were failing.
So edited in the commands.py so that the build should pass (return 0) only if all the tests passed.
*Test plan (required)**
The travis build should now fail if the tests fail
**Closing issues** #514 
Put `closes #XXXX` in your comment and commit message to auto-close the issue that your PR fixes (if such).
=> Fix test failing issue

OAuthdSetup.md
Provided necessary details in the setup guide.
=> Modified OAuthd setup guide for easy setup of OAuth service

README.md
1. Fixed the directory issues in README.md clearly representing wherever there's a need to change the directory.
2. Added fixes for possible errors that the user may encounter while installation. All those errors were encountered by me @saurav9878 while installation.
3. Corrected Indentation issues of markdown.
4. Added syntax highlighting for bash commands.
5. Fix broken links like localhost:3000
Fixes issue #534
=> Updated readme to fix broken links and missing directories issue
